name: Build
description: 'build artifact'

inputs:
  environment:
    description: environment
    required: false
    type: string
outputs:
  mvnOutput:
    description: mvn build results
    value: ${{ steps.mvn.outcome }}
        
runs:
  using: "composite"
  steps:    
    - name: Build with Maven
      id: mvn
      shell: bash
      run: mvn clean install
